Сохранение состояния окна
NorraBjornen/Robots-1 pull request #2
Opened 2020-04-25 13:45 UTC by NorraBjornen

@shaykemelov второе задание

2020-04-26 15:07 UTC, shaykemelov commented on robots/src/logic/StateSaver.java
> +public class StateSaver {
По-моему класс и методы получились слишком большими. И как-то далеко все ушло от ООП и SOLID.
Предлагаю сделать какой-нибудь интерфейс, в котором будут объявлены два метода `saveState` и `restoreState`. И например окна, состояния которых нам нужно сохранять, будут реализовывать данный интерфейс. А уже этот класс будет вызывать методы save/restore и заниматься сохранением/чтением состояния из файла.

Например
```
...
var savedState = loadSavedStateFromDisk()
frame.restoreState(savedState)
...
```

Уже в методе `frame.restoreState(savedState)` будет происходить восстановление состояния `logWindow` и `gameWindow`

```
...
this.logWindow.restoreState(savedState.logWindowState)
this.gameWindow.restoreState(savedState,gameWindowState)
...
```

2020-04-27 13:11 UTC, NorraBjornen commented
@shaykemelov Исправил

2020-04-27 19:31 UTC, shaykemelov requested changes
tofix

2020-04-27 19:31 UTC, shaykemelov commented on robots/src/gui/DialogOnCloseAdapter.java
> +            frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
желательно оборачивать в скобки, даже если это единственное выражение

2020-04-27 19:31 UTC, shaykemelov commented on robots/src/gui/internal/frames/AbstractInternalFrame.java
> +     * Возращает объект типа WindowState с текущими шириной, высотой, координатами и видимостью окна
Воз`в`ращает

2020-04-27 19:31 UTC, shaykemelov commented on robots/src/gui/internal/frames/AbstractInternalFrame.java
> +     * Возращает объект типа WindowState с текущими шириной, высотой, координатами и видимостью окна
Раз уж метод возвращет состояние, то предлагаю переименовать его в getState

2020-04-27 19:31 UTC, shaykemelov commented on robots/src/gui/internal/frames/AbstractInternalFrame.java
> +    public void restoreState(WindowState state) {
а здесь в setState

2020-04-27 19:31 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    private GameWindow createGameWindow() {
метод может быть `static`

2020-04-27 19:31 UTC, shaykemelov commented on robots/src/logic/state/WindowState.java
> +public class WindowState implements Serializable {
надо бы добавить `serialVersionUID`

2020-04-27 19:31 UTC, shaykemelov commented on robots/src/logic/state/StateSaveable.java
> +}
предлагаю переименовать интерфейс в `HasState` с методами `WindowState getState()` и `void setState(WindowState state)`

2020-04-27 19:31 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +        Map<String, WindowState> states = diskStateSaver.loadFromDisk();
Неправильно, что `MainApplicationFrame` знает что-либо о механизме сохраненеия/чтения состояния с/из файловой системы, это не должно входить в обязанности фрейма

2020-04-28 03:12 UTC, NorraBjornen commented
@shaykemelov Исправил

2020-04-28 06:49 UTC, merged