Task 4
NorraBjornen/Robots-1 pull request #4
Opened 2020-05-26 12:44 UTC by NorraBjornen

@shaykemelov 4-е задание

2020-05-26 18:34 UTC, shaykemelov requested changes
tofix

2020-05-26 18:34 UTC, shaykemelov commented on robots/src/gui/internal/frames/LogWindow.java
>      private TextArea m_logContent;
`private final`

2020-05-26 18:34 UTC, shaykemelov commented on robots/src/gui/internal/frames/LogWindow.java
> +        LogChangeListener listener = this;
эта переменная все-таки избыточна

2020-05-26 18:34 UTC, shaykemelov commented on robots/src/gui/internal/frames/LogWindow.java
> +                m_logSource.unregisterListener(listener);
тут можно вот так `LogWindow.this`

2020-05-26 18:34 UTC, shaykemelov commented on robots/src/log/LogWindowSource.java
> +    private int queueLength;
если мы не собираемся крутить данный параметр в рантайме, то пометь его как `final`

2020-05-26 18:34 UTC, shaykemelov commented on robots/src/log/LogWindowSource.java
> +        subscribers = new ArrayList<>();
можно заменить `ArrayList` на `CopyOnWriteArrayList` и тогда не нужно будет руками синхронизировать методы `registerListener`, `unregisterListener`

2020-05-26 18:34 UTC, shaykemelov commented on robots/src/log/LogWindowSource.java
> +    private LinkedList<LogEntry> messages;
пометь поле как `final`

2020-05-26 18:34 UTC, shaykemelov commented on robots/src/log/LogWindowSource.java
> +        synchronized (subscribers) {
не совсем понятно - для чего тут идет синхронизация на подписчиках

2020-05-26 18:34 UTC, shaykemelov commented on robots/src/log/LogWindowSource.java
>      }
метод не потокобезопасен

`messages.subList(startFrom, indexTo);` возвращает список, который привязан к `messages`. любое изменение подсписка приводит к изменению `messages`
вот пример
```
    public static void main(String[] args)
    {
        List<Object> objects = new ArrayList<>();

        for (int i = 0; i < 10; i++)
        {
            objects.add(new Object());
        }

        System.out.println(objects.size());

        objects.subList(0, 5).clear();

        System.out.println(objects.size());
    }
```

2020-05-26 18:34 UTC, shaykemelov commented on robots/src/log/LogWindowSource.java
>      }
этот метод тоже не потокобезопасен. извне можно добавлять новые объекты в список и удалять. в итоге нет никаких синхронизаций и ограничений на кол-во объектов в списке

2020-05-26 18:34 UTC, shaykemelov commented on robots/src/log/Logger.java
> +        messageNumber++;
а почему тогда у нас кол-во сообщений в методе `error` не увеличивается?

2020-05-26 18:34 UTC, shaykemelov commented on robots/src/log/Logger.java
> +    private static int messageNumber = 0;
конечно сейчас эта переменная изменяется только из `UI` потока, но в общем такие штуки делают как `AtomicInteger` для потокобезопасности

2020-05-27 04:50 UTC, NorraBjornen commented
@shaykemelov сделал исправления

2020-06-02 23:59 UTC, shaykemelov requested changes
tofix

2020-06-02 23:59 UTC, shaykemelov commented on robots/src/log/Logger.java
> +    private static AtomicInteger messageNumber = new AtomicInteger(0);
`final`

2020-06-02 23:59 UTC, shaykemelov commented on robots/src/log/LogWindowSource.java
> +    private LinkedList<LogEntry> messages;
!

2020-06-02 23:59 UTC, shaykemelov commented on robots/src/log/LogWindowSource.java
> +    private final CopyOnWriteArrayList<LogChangeListener> subscribers;
зачем лишний раз завязываться на реализации, когда можно указать интерфейс
`CopyOnWriteArrayList` -> `List`

2020-06-09 10:56 UTC, NorraBjornen commented
@shaykemelov Исправлено

2020-06-09 10:59 UTC, shaykemelov approved these changes
lgtm

2020-06-09 10:59 UTC, merged