Локализация приложения
NorraBjornen/Robots-1 pull request #5
Opened 2020-06-09 12:43 UTC by NorraBjornen

@shaykemelov 5 задание. Сделана локализация. Локаль создается с указанными параметрами (выбор языка) в классе RobotsProgram, затем передается как зависимость дальше

2020-06-09 15:23 UTC, shaykemelov requested changes
Не вижу возможности переключения локали для пользователя
По заданию необходимо `обеспечить возможность выбора языка, на котором работает пользовательский интерфейс`

tofix

2020-06-09 15:25 UTC, shaykemelov commented
пользователь должен иметь возможность переключать язык интерфейса. у него ведь нет возможности взять исходники, что-то там поменять и скомпилировать приложение

2020-06-09 16:07 UTC, NorraBjornen commented
@shaykemelov добавил пункт меню, который позволяет менять язык

2020-06-13 13:25 UTC, shaykemelov approved these changes
чет жестко вышло, что пользователь должен каждый раз язык переключать. ну в задании явно не указано

lgtm :)

2020-06-13 13:25 UTC, merged